# Generated by Django 3.0.2 on 2020-01-28 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rideowner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=100)),
                ('arrive_date', models.DateTimeField(help_text='Format: 2020-01-01 12:00')),
                ('passenger_num', models.PositiveIntegerField()),
                ('whether_share', models.BooleanField()),
                ('required_type', models.CharField(blank=True, max_length=200)),
                ('required_special', models.CharField(blank=True, max_length=400)),
                ('status', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
