# Generated by Django 3.0.2 on 2020-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20200129_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideowner',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
