# Generated by Django 3.0.2 on 2020-01-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_auto_20200129_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideowner',
            name='required_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('SEDAN', 'SEDAN'), ('COUPE', 'COUPE'), ('--', '--')], default='--', max_length=20),
        ),
    ]
