# Generated by Django 3.0.2 on 2020-01-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_auto_20200131_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideowner',
            name='share_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
