# Generated by Django 3.0.2 on 2020-02-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_auto_20200131_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideowner',
            name='max_share_num',
            field=models.PositiveIntegerField(default=0, help_text='If you do not want to share please choose 0'),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='passenger_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='passenger_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
