# Generated by Django 3.0.2 on 2020-01-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_info',
            name='license_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driver_info',
            name='max_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver_info',
            name='special_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='driver_info',
            name='vehicle_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
