# Generated by Django 3.0.2 on 2020-01-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200128_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_info',
            name='special_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
