# Generated by Django 3.0.2 on 2020-01-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200129_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_info',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('COMPACT', 'COMPACT'), ('SEDAN', 'SEDAN'), ('COUPE', 'COUPE'), ('', '')], default='', max_length=20),
        ),
    ]
