# Generated by Django 3.0.2 on 2020-02-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200129_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_info',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
